# Generated by Django 5.2.5 on 2025-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=225)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(null=True)),
                ('ai_summary_en', models.TextField(blank=True)),
                ('ai_summary_tl', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
